# Generated by Django 5.2.13 on 2026-04-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otptoken',
            new_name='notificatio_user_id_90d88c_idx',
            old_name='notif_otp_user_idx',
        ),
        migrations.AlterField(
            model_name='usertwofaprofile',
            name='preferred_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('totp', 'Authenticator App (TOTP)'), ('face', 'Face Recognition')], default='email', max_length=10),
        ),
    ]
