# Generated by Django 5.2.13 on 2026-04-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facelivenesschallenge',
            new_name='face_auth_f_is_used_b7f752_idx',
            old_name='face_liveness_idx',
        ),
        migrations.AlterField(
            model_name='userfaceprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
