"""Models for trading signals."""
from django.db import models


class TradingSignal(models.Model):
    """Alpha signal generated by the multi-agent system."""
    DIRECTION_CHOICES = [
        ("BUY", "Buy"),
        ("SELL", "Sell"),
        ("NEUTRAL", "Neutral"),
    ]

    pair = models.CharField(max_length=10)  # e.g. EURUSD
    direction = models.CharField(max_length=10, choices=DIRECTION_CHOICES)
    confidence = models.FloatField()  # 0.0 to 1.0
    macro_score = models.FloatField(default=0.0)
    technical_score = models.FloatField(default=0.0)
    sentiment_score = models.FloatField(default=0.0)
    consensus_count = models.IntegerField(default=0)  # agents agreeing
    rationale = models.TextField(blank=True)
    entry_price = models.FloatField(null=True)
    stop_loss = models.FloatField(null=True)
    take_profit = models.FloatField(null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    closed_at = models.DateTimeField(null=True, blank=True)
    pnl = models.FloatField(null=True, blank=True)

    class Meta:
        db_table = "trading_signals"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.pair} {self.direction} ({self.confidence:.0%})"
