# Generated by Django 5.2.13 on 2026-04-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(db_index=True, max_length=6)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('size', models.FloatField(default=0.1)),
                ('entry_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], db_index=True, default='OPEN', max_length=6)),
                ('pnl', models.FloatField(default=0.0)),
                ('pnl_pct', models.FloatField(default=0.0)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline_snapshot', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paper Position',
                'verbose_name_plural': 'Paper Positions',
                'ordering': ['-opened_at'],
            },
        ),
    ]
