# Generated by Django 5.2.11 on 2026-04-29 09:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(db_index=True, max_length=50)),
                ('pair', models.CharField(db_index=True, max_length=6)),
                ('signal_direction', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('NEUTRAL', 'NEUTRAL')], max_length=7)),
                ('confidence', models.FloatField(default=0.0)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('pnl', models.FloatField(blank=True, help_text="P&L attributed to this agent's contribution", null=True)),
                ('weight_used', models.FloatField(default=0.0, help_text='Dynamic weight at time of signal')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('paper_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_outcomes', to='paper_trading.paperposition')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_name', 'created_at'], name='paper_tradi_agent_n_b6a734_idx')],
            },
        ),
    ]
