# Generated by Django 5.2.13 on 2026-06-09 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0002_agentoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(db_index=True, max_length=6)),
                ('direction', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('HOLD', 'HOLD'), ('NEUTRAL', 'NEUTRAL')], default='HOLD', max_length=8)),
                ('confidence', models.FloatField(default=0.0)),
                ('decision', models.CharField(choices=[('APPROVED', 'APPROVED'), ('APPROVED_MODIFIED', 'APPROVED_MODIFIED'), ('REJECTED', 'REJECTED'), ('BLOCKED', 'BLOCKED'), ('ERROR', 'ERROR')], db_index=True, default='REJECTED', max_length=20)),
                ('market_regime', models.CharField(blank=True, default='', max_length=32)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('paper_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_logs', to='paper_trading.paperposition')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pair', 'created_at'], name='paper_tradi_pair_3c94c2_idx'), models.Index(fields=['decision', 'created_at'], name='paper_tradi_decisio_a5a46d_idx')],
            },
        ),
    ]
