"""
Paper Trading Models
Stores simulated positions and trades generated by the AI pipeline.
"""
from django.db import models
from django.utils import timezone


class PaperPosition(models.Model):
    """An open or closed simulated trading position."""

    SIDE_CHOICES = [("BUY", "BUY"), ("SELL", "SELL")]
    STATUS_CHOICES = [("OPEN", "OPEN"), ("CLOSED", "CLOSED")]

    pair = models.CharField(max_length=6, db_index=True)
    side = models.CharField(max_length=4, choices=SIDE_CHOICES)
    size = models.FloatField(default=0.1)
    entry_price = models.FloatField()
    current_price = models.FloatField()
    stop_loss = models.FloatField(null=True, blank=True)
    take_profit = models.FloatField(null=True, blank=True)
    status = models.CharField(max_length=6, choices=STATUS_CHOICES, default="OPEN", db_index=True)

    # P&L
    pnl = models.FloatField(default=0.0)
    pnl_pct = models.FloatField(default=0.0)

    # Timestamps
    opened_at = models.DateTimeField(auto_now_add=True, db_index=True)
    closed_at = models.DateTimeField(null=True, blank=True)

    # Store the full pipeline decision that triggered this trade
    pipeline_snapshot = models.JSONField(null=True, blank=True)

    class Meta:
        ordering = ["-opened_at"]
        verbose_name = "Paper Position"
        verbose_name_plural = "Paper Positions"

    def __str__(self):
        return f"{self.side} {self.pair} @ {self.entry_price} [{self.status}]"

    @property
    def pip_value(self):
        """Approximate pip value for P&L calculation."""
        return 0.01 if "JPY" in self.pair else 0.0001

    def calculate_pnl(self) -> float:
        """Calculate unrealised P&L in account currency (USD)."""
        pip_diff = (self.current_price - self.entry_price) / self.pip_value
        if self.side == "SELL":
            pip_diff = -pip_diff
        # Approximate: 1 pip = $10 for 1 standard lot
        return round(pip_diff * self.size * 10, 2)


class AgentOutcome(models.Model):
    """
    Records per-agent accuracy for every settled paper trade.
    Written by the settler service; read by PerformanceTracker.
    """

    DIRECTION_CHOICES = [("BUY", "BUY"), ("SELL", "SELL"), ("NEUTRAL", "NEUTRAL")]

    agent_name = models.CharField(max_length=50, db_index=True)
    pair = models.CharField(max_length=6, db_index=True)
    signal_direction = models.CharField(max_length=7, choices=DIRECTION_CHOICES)
    confidence = models.FloatField(default=0.0)
    was_correct = models.BooleanField(null=True, blank=True)
    pnl = models.FloatField(null=True, blank=True, help_text="P&L attributed to this agent's contribution")
    weight_used = models.FloatField(default=0.0, help_text="Dynamic weight at time of signal")

    paper_position = models.ForeignKey(
        PaperPosition,
        on_delete=models.CASCADE,
        related_name="agent_outcomes",
        null=True,
        blank=True,
    )

    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["agent_name", "created_at"]),
        ]

    def __str__(self):
        correct_str = "correct" if self.was_correct else "wrong" if self.was_correct is not None else "pending"
        return f"{self.agent_name} {self.signal_direction} {self.pair} [{correct_str}]"
