# Generated by Django 5.2.13 on 2026-04-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('news', 'News'), ('macro', 'Macro'), ('ohlcv', 'OHLCV')], db_index=True, max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_inserted', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(db_index=True, max_length=50)),
                ('indicator_name', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('series_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.URLField(blank=True, default='', max_length=800)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('currencies', models.JSONField(default=list)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['published_at'], name='scheduling__publish_0e75e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='OHLCVCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('timeframe', models.CharField(choices=[('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', 'Daily')], db_index=True, max_length=5)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
    ]
